### ISSUE TITLE
1ms flash of previous page

### ISSUE THREAD

**Issue by jrowny** [ajoslin/angular-mobile-nav#10]
sometimes when going back I get a 1ms flash of the previous page. Not sure if it's because I'm using the back button instead of $navigate.back.

**Comment by jrowny** [comment]
So I found this comment in change.js on line 59 which revealed that I had the wrong z-index on one element. Changing my z-index on that element to a positive number fixes this issue.

**Comment by jrowny** [comment]
nevermind, I still get the flash sometimes :(

**Comment by jrowny** [comment]
Looks like this may be the culprit/fix, trying it now:
https://github.com/Diveboard/jquery-mobile/commit/ff125b65e682ecd33888a6db1221ac441d258994

**Comment by jrowny** [comment]
Looks like there's 5 or 6 different fixes floating around, haven't gotten any to work yet. Only seems to affect phonegap very badly. Chrome does it like 1 in 5 or 6 transitions but the flickr is much less pronounced.

**Comment by ajoslin** [comment]
Tried to fix this last night after a few minutes' tinkering, no progress yet.  Thanks for looking into it so much.  

(btw, this bug comes up on emulate.phonegap.com too, so it's easier to test)

**Comment by jrowny** [comment]
Yea, I can make it reproduce on the emulator but much more noticeable on device or a "real" emulator. I can even get it to happen occasionally in the latest chrome for android.

**Comment by jrowny** [comment]
So i've looked at a few different frameworks that seem to do things okay. One thing I noticed is that you set z-index to 0 on components, but I'm not sure it's ever set back so eventually everything will be z-index 0, right? Sencha seems to keep track of all view's z-index and sets them accordingly. Another thing is that many frameworks I've looked at (such as Sencha) define the CSS transitions via javascript for more flexibility. 

Here's a view navigator (not for AngularJS) that seems to work okay, it's called AppUI: https://github.com/triceam/app-UI/blob/master/src/viewnavigator/viewnavigator.js I noticed there's a comment in the source about using duration+90ms instead of webkittransitionend because apparently it's a bit buggy.

**Comment by jrowny** [comment]
Looks like AppUI uses https://github.com/benbarnett/jQuery-Animate-Enhanced to do transitions.

**Comment by ajoslin** [comment]
The source.css() thing is just setting the CSS on the page going out, just before its removed. That should be changed to -10, not 0. 

There are still some other problems besides that though... Please feel free to keep tinkering. 

I won't have time to look at this again until next week, by the way.

**Comment by jrowny** [comment]
I replaced the animation with jquery enhanced animate and it's working okay now. Obviously you don't want to have that as a dependency so we''ll have to dig into enhanced animate and see why that works.

**Comment by jrowny** [comment]
And that was a pain in the butt, but I figured it out.

In the phonegap project I just had to open AndroidManifest.xml and turn off hardware acceleration.

**Comment by jrowny** [comment]
sigh, nevermind.. it still shows up sometimes.

**Comment by ajoslin** [comment]
Thanks for all the work Jonathan .. We will fix this somehow.  I'll look at it Tuesday.

**Comment by ajoslin** [comment]
I haven't had any time yet, but have a few ideas!

**Comment by ajoslin** [comment]
I think I fixed it in the last commit.  I did the z-index thing, and also did the force reflow thing by setting element's offsetWidth, which forced the z-index to apply. https://github.com/ajoslin/angular-mobile-nav/commit/14a18f696b729b1edb678e05f4b3972daca0fc1b#L1R40. Could you test it on your setup?

I also fixed the modal out animation flickering once it ends.  I fixed this by setting -webkit-animation-fill-mode to forwards on all pages, so that all the styles applied at the end of the webkit animations stay on the element after the anim is done.

I also renamed `dest` and `source` to `next` and `prev`, it makes a lot more sense.

**Comment by jrowny** [comment]
Okay, I'll give this a shot tonight. Other suggestions I commonly hear are to add backface visibility hidden and translate3d(0,0,0) to the default classes. Since that's easy to add, I'll test it both ways.

**Comment by jrowny** [comment]
Thanks so much, it's working great now!

**Comment by whitneyland** [comment]
I'm still seeing this bug, just verified that I have changes from the last patch.

Is anyone else still seeing it?  If not would it be helpful to upload a minimum test case project?

**Comment by jrowny** [comment]
I still see it on Android 2.x, but I'm not sure that's fixable. Adding the translate3d:(0,0,0) and backface-visibility:hidden does also help. On Android 4.x I need to disable hardware acceleration for it to be smooth, which seems counter-intuitive.

**Comment by whitneyland** [comment]
I see it on Chrome desktop, and Safari iPad iOS v6.01.  Straight browsing no PhoneGap.

I agree forget Android 2.x, but webkit problems are a killer.

What do I have to do to get it reopened?

**Comment by whitneyland** [comment]
I've created a small example of the problem here: http://amnav.kissr.com

Opened a new issue since it looks like this one (#10) is not affecting new devices.
https://github.com/ajoslin/angular-mobile-nav/issues/12

**Comment by inscapist** [comment]
Hi all, i am using the latest build and still having this issue using phonegap, on Asus Meepad, Android 4.1.1. The navigation is triggered by $navigate.go. I tried disabling hardware overlay too. Can anyone help? Thanks

**Comment by ajoslin** [comment]
Hi @sagittaros,

Does your mobile-nav.css have '-webkit-backface-visibility: none' near the top?  To be sure it's the newest version.

I guess the file should come with a version name in it .. :smile:

**Comment by inscapist** [comment]
Hi @ajoslin , thanks for the prompt response! It was a clean make from master branch and is similar to https://github.com/ajoslin/angular-mobile-nav/blob/gh-pages/mobile-nav.css.

I don't find any "webkit-backface" in there though.

**Comment by ajoslin** [comment]
Oh, weird! I thought I committed that fix.  It's a fix for some android device flickers.  Try making the newest master commit.

**Comment by inscapist** [comment]
awesome, i applied the commit, i don't have the device with me now, will test it tomorrow =)

**Comment by artworkad** [comment]
I see the flash too but only in ripple phonegap emulator. When viewing the demo from android 4.1.2 browser there is no flash.
